version: '2'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  zookeeper_data:
    driver: local
    
  kafka_data:
    driver: local


  